### ISSUE TITLE
Reversing a python list without a temporary variable.

### ISSUE THREAD

**Issue by srijitendrasatpathy** [cherry324/Datastructures-and-Algorithms-using-Python#1]
I think the title of the file should be reversing python list containing numbers rather than just reversing a python list. As I understand python list can hold heterogeneous objects. In this case, the first two approaches will work but not the final approach.

**Comment by Bhargavacharanreddy** [comment]
Thanks for pointing it out. I have changed the title of that particular file. It's for a list containing only numbers as data elements in it.
